{% set version="0.26.1" %}

package:
  name: cython
  version: {{ version }}

source:
  fn: Cython-{{ version }}.tar.gz
  url: https://github.com/cython/cython/archive/{{ version }}.tar.gz
  sha256: fcb0f3131f0ac186368dc1df0b70e2b5b1f4de94d74173044cfd3beff81e4255

build:
  number: 0
  entry_points:
    - cython = Cython.Compiler.Main:setuptools_main
    - cythonize = Cython.Build.Cythonize:main
    - cygdb = Cython.Debugger.Cygdb:main

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  commands:
    - cython --version
  files:
    - fib.pyx

about:
  home: http://www.cython.org/
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: The Cython compiler for writing C extensions for the Python language
  description: |
    Cython is an optimising static compiler for both the Python programming
    language and the extended Cython programming language. It makes writing C
    extensions for Python as easy as Python itself.
  doc_url: http://cython.org/#documentation
  dev_url: https://github.com/cython/cython

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - ocefpaf
    - synapticarbors
    - mingwandroid
