{% set version = "0.29.27" %}

package:
  name: cython
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/C/Cython/Cython-{{ version }}.tar.gz
  sha256: c6a442504db906dfc13a480e96850cced994ecdc076bcf492c43515b78f70da2
  patches:
    # xref: https://github.com/cython/cython/pull/4236
    - patches/pypy37-eval.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - cython = Cython.Compiler.Main:setuptools_main
    - cythonize = Cython.Build.Cythonize:main
    - cygdb = Cython.Debugger.Cygdb:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}  # [not (linux and aarch64)]
    - patch                  # [not win]
    - m2-patch               # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
    - cython --version
  files:
    - fib.pyx

about:
  home: https://cython.org/
  license: Apache-2.0
  license_file: LICENSE.txt
  license_family: Apache
  summary: The Cython compiler for writing C extensions for the Python language
  description: |
    Cython is an optimising static compiler for both the Python programming
    language and the extended Cython programming language. It makes writing C
    extensions for Python as easy as Python itself.
  doc_url: https://cython.org/#documentation
  dev_url: https://github.com/cython/cython

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - ocefpaf
    - synapticarbors
    - isuruf
    - scopatz
    - katietz
