{% set name = "cython" %}
{% set version = "3.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cython-{{ version }}.tar.gz
  sha256: 7146dd2af8682b4ca61331851e6aebce9fe5158e75300343f80c07ca80b1faff

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - cython = Cython.Compiler.Main:setuptools_main
    - cythonize = Cython.Build.Cythonize:main
    - cygdb = Cython.Debugger.Cygdb:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  files:
    - fib.pyx
  requires:
    - pip
    - setuptools
    - {{ compiler('c') }}
    # for runtests.py
    #- numpy
    #- pythran
  commands:
    - pip check
    - cython --version
    - cython --help
    - cythonize --help
    - cygdb --help
    # 2023/12/19: The upstream test suite is quite slow.
    # It requires files: `runtests.py`, the folder `tests/`, and dependencies: setuptools, numpy and pythran (optionally).
    # If you want to run refnanny tests then add to source_files `Cython/Runtime/refnanny.pyx` and remove --no-refnanny flag.
    #- python runtests.py -v --no-doctest --no-pyregr --no-code-style --no-refnanny --annotate
    # source_files:
    #   - runtests.py
    #   - tests/

about:
  home: https://cython.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: The Cython compiler for writing C extensions for the Python language
  description: |
    Cython is an optimising static compiler for both the Python programming
    language and the extended Cython programming language. It makes writing C
    extensions for Python as easy as Python itself.
  doc_url: https://cython.readthedocs.io/
  dev_url: https://github.com/cython/cython

extra:
  recipe-maintainers:
    - cbouss
