{% set name = "cython" %}
{% set version = "0.29.30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/C/Cython/Cython-{{ version }}.tar.gz
  sha256: 2235b62da8fe6fa8b99422c8e583f2fb95e143867d337b5c75e4b9a1a865f9e3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - cython = Cython.Compiler.Main:setuptools_main
    - cythonize = Cython.Build.Cythonize:main
    - cygdb = Cython.Debugger.Cygdb:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}  # [not (linux and aarch64)]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - Cython
    - Cython.Build
    - Cython.Compiler
    - Cython.Runtime
    - Cython.Distutils
    - Cython.Debugger
    - Cython.Debugger.Tests
    - Cython.Plex
    - Cython.Tests
    - Cython.Build.Tests
    - Cython.Compiler.Tests
    - Cython.Utility
    - Cython.Tempita
    - pyximport
  requires:
    - pip
  commands:
    - pip check
    - cython --version
    - cython --help
    - cythonize --help
    - cygdb --help
  files:
    - fib.pyx

about:
  home: https://cython.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: The Cython compiler for writing C extensions for the Python language
  description: |
    Cython is an optimising static compiler for both the Python programming
    language and the extended Cython programming language. It makes writing C
    extensions for Python as easy as Python itself.
  doc_url: https://cython.org/#documentation
  dev_url: https://github.com/cython/cython

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - ocefpaf
    - synapticarbors
    - isuruf
    - scopatz
    - katietz
