travis:
  secure:
    BINSTAR_TOKEN: DcRri3GXqzT9H7xA99lInMS0zdxu8wciSpSdHmlk4cXaU2eT8TiYoSE2h4kNZ04INFWdwGPjPck/SBV3cg0EO4ezxFSjFsiZQ4h09AwsB9QAvFnor91Dj+0UrlApsnNComTtbgSh8caytosN/8EyaOriskf6BZQ87abFp8k9NmG6iOVOUPWxUnrOALrn3l00NOvkxO3uj9w8b0H0oa/Gs6OXC8axOqqscGLQch0H733jWwgauCZ55a632DN7fhlcCNhvVqEUPq7tZR9RM57Pgv4fxo7vbcH3I96eYkW8Sf9RekxVJXhVtO6Q16Wq9B5sWgrF8VEY64PVNAqGewxpTAgFy2u7unOlnCzixvbkrA1FTJFgvTIK5eGD17FB2MUVYTF1ulSaHSZioLUlCJHs+OETzEzyk6AsIWLBve/BkrIpWwgWwzNNyV1xYMrbVFpB1mD6ATCSmFli4uEs8y/Sn2Ws2h0uMQSkf8N93xi+VNLzHd85e6TBMFDspo118xgpuyULtJuYmGfQJqpGJPKZ+DAVMZcVsbQV/iFbAPMbPELDopqKbkm0nzO4XHULKuNyb+fxzalYgUBQRxyQ3WV/47gC4r46iIakjNKiydyuNpj/jfsvTW4OYLLV8fYmApcV+UG+runKE4c6hUeBLOcgdK1Tl2P5Pou1ynp/QiosGfU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
